# Generated by Django 5.2.2 on 2025-06-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0003_chatgroup_is_private_chatgroup_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default='g7LDFDgzYGy8ramRQffoQ2', max_length=128, unique=True),
        ),
    ]
