# Generated by Django 5.2.2 on 2025-06-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0005_chatgroup_is_bot_chat_chatmessage_is_bot_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default='CQu89mRrffs2dqaa7qSUdr', max_length=128, unique=True),
        ),
    ]
