# Generated by Django 5.2.2 on 2025-06-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0006_alter_chatgroup_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default='NGNfiby5Mk7LkwUUQWGFfy', max_length=128, unique=True),
        ),
    ]
