# Generated by Django 5.2.2 on 2025-06-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0007_alter_chatgroup_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='is_bot_chat',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_bot_message',
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default='J4g8dfk7YV2tpVX3hEHLQo', max_length=128, unique=True),
        ),
        migrations.DeleteModel(
            name='UserPreferences',
        ),
    ]
