# Generated by Django 5.2.2 on 2025-06-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0008_remove_chatgroup_is_bot_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], null=True),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default='b3NfjRQKdcNBPvEGT8kUiD', max_length=128, unique=True),
        ),
    ]
