# Generated by Django 5.2.2 on 2025-06-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0009_chatgroup_age_chatgroup_country_chatgroup_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='age',
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='country',
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='gender',
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default='VYLgiMfdz4668KvqbZJSmm', max_length=128, unique=True),
        ),
    ]
