# Generated by Django 5.2.2 on 2025-06-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0010_remove_chatgroup_age_remove_chatgroup_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default='2Gwoc3NWXxg6bjqoQY9MH7', max_length=128, unique=True),
        ),
    ]
