# Generated by Django 5.2.2 on 2025-06-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mmr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(blank=True, choices=[(1, 'carry'), (2, 'mid'), (3, 'offlane'), (4, 'support'), (5, 'fullsupport')], null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='steam_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
