# Generated by Django 5.2.2 on 2025-06-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_bio_alter_customuser_mmr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
        migrations.AddField(
            model_name='customuser',
            name='steam_avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='steam_nickname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
