# Generated by Django 5.2.2 on 2025-06-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_steam_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(blank=True, choices=[(1, 'Carry'), (2, 'Mid'), (3, 'Offlane'), (4, 'Support'), (5, 'Hard Support')], null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='steam_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
