# Generated by Django 5.2.2 on 2025-06-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_role_alter_customuser_steam_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
