# Generated by Django 5.2.2 on 2025-06-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='rank_icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mmr',
        ),
        migrations.AddField(
            model_name='customuser',
            name='rank',
            field=models.ImageField(blank=True, null=True, upload_to='rank_icons/'),
        ),
    ]
