# Generated by Django 5.2.2 on 2025-06-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rankimage_remove_customuser_mmr_customuser_rank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RankImage',
        ),
        migrations.AddField(
            model_name='customuser',
            name='losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='win_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='steam_id',
            field=models.CharField(blank=True, help_text='SteamID64 (17-значный идентификатор)', max_length=17, null=True, unique=True),
        ),
    ]
