# Generated by Django 5.2.2 on 2025-06-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_rankimage_customuser_losses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
