# Generated by Django 5.2.2 on 2025-06-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.CharField(blank=True, default='0-0', max_length=50, null=True),
        ),
    ]
