# Generated by Django 5.2.2 on 2025-06-13 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_rank'),
    ]

    operations = [
    ]
