# Generated by Django 5.2.2 on 2025-06-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_set_default_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mmr',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='steam_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
