# Generated by Django 5.2.2 on 2025-06-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_mmr_alter_customuser_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
