# Generated by Django 5.2.2 on 2025-06-17 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customuser_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mmr',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('any', 'Любая'), ('carry', 'Керри'), ('mid', 'Мид'), ('offlane', 'Оффлейн'), ('support', 'Саппорт'), ('hard_support', 'Хард саппорт')], default='any', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='steam_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='steam_nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id', models.CharField(blank=True, max_length=50, null=True)),
                ('steam_nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('any', 'Любая'), ('carry', 'Керри'), ('mid', 'Мид'), ('offlane', 'Оффлейн'), ('support', 'Саппорт'), ('hard_support', 'Хард саппорт')], default='any', max_length=20)),
                ('availability', models.CharField(choices=[('any', 'Любое время'), ('morning', 'Утро (6:00 - 12:00)'), ('day', 'День (12:00 - 18:00)'), ('evening', 'Вечер (18:00 - 00:00)'), ('night', 'Ночь (00:00 - 6:00)')], default='any', max_length=20)),
                ('mmr', models.IntegerField(default=0)),
                ('rank', models.CharField(blank=True, max_length=50, null=True)),
                ('win_rate', models.FloatField(default=0.0)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
