# Generated by Django 5.2.2 on 2025-06-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_customuser_last_updated_customuser_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
